### ISSUE TITLE
Weird error when sending mail using `contact me`

### ISSUE THREAD

**Issue by DevInfinix** [the-indian-dev/personal-website#2]
error:
```
{"errors":[{"message":"Submitting data from \"https://theindiandev.in\" is not supported."}]}
```
Please fix it, since I need to contact the very epok OP developer of this website 🙏

**Comment by DevInfinix** [comment]
@the-indian-dev

**Comment by daiyosei** [comment]
I have disabled it, in favour of you using the social media buttons

**Comment by DevInfinix** [comment]
Would highly suggest @the-indian-dev  to hide the button, as it's quite misleading, annoying and of no use at this point.

Also, is the project open for accepting contributions? The light theme sucks, and I would like to contribute to the website by working on the new release.

Thank you
Regards,
INFINIX (Epok Dev)

**Comment by daiyosei** [comment]
no
